---
abstract: 'Implements the Amazon Web Services signature version 4, AWS4-HMAC-SHA256'
author:
  - 'Tim Nordenfur <tim@gurka.se>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Amazon-Signature-V4
no_index:
  directory:
    - t
    - inc
requires:
  DateTime::Format::Strptime: 0
  Digest::SHA: 0
  File::Slurp: 0
  HTTP::Request: 0
  Test::More: 0
  URI::Escape: 0
  perl: 0
version: 0.14
